  CREATE TABLE "TT_OBJECT_TYPES" 
   (	"OBJECT_TYPE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(20,0), 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"ISCLASS" NUMBER(1,0), 
	"ISSYSTEM" NUMBER(1,0), 
	"ISSEARCHABLE" NUMBER(1,0) DEFAULT 1, 
	"ALIAS" VARCHAR2(255 BYTE), 
	"FLAGS" NUMBER(10,0) DEFAULT 0, 
	"PROPERTIES" VARCHAR2(4000 BYTE), 
	"ISABSTRACT" NUMBER(1,0), 
	"INTERNAL_NAME" VARCHAR2(200 BYTE), 
	 CONSTRAINT "XPKTT_OBJECT_TYPES" PRIMARY KEY ("OBJECT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT), 
	 UNIQUE ("INTERNAL_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT), 
	 CONSTRAINT "R_13" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "TT_OBJECT_TYPES" ("OBJECT_TYPE_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

  CREATE TABLE "TT_OBJECTS" 
   (	"OBJECT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(20,0), 
	"OBJECT_TYPE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"OBJECT_CLASS_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER(20,0), 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ORDER_NUMBER" NUMBER(10,0), 
	"VERSION" NUMBER(20,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "XPKTT_OBJECTS" PRIMARY KEY ("OBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT), 
	 CONSTRAINT "R_14" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE DEFERRABLE ENABLE, 
	 CONSTRAINT "R_34" FOREIGN KEY ("OBJECT_TYPE_ID")
	  REFERENCES "TT_OBJECT_TYPES" ("OBJECT_TYPE_ID") ENABLE, 
	 CONSTRAINT "R_35" FOREIGN KEY ("OBJECT_CLASS_ID")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "R_89" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  CREATE TABLE "TT_ATTRIBUTES" 
   (	"ATTR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE), 
	"ATTR_ACCESS_TYPE" NUMBER(10,0) DEFAULT 0, 
	"ISMULTIPLE" NUMBER(1,0), 
	"ISEXTGENERATED" NUMBER(1,0), 
	"ISEXTSTORED" NUMBER(1,0), 
	"ADAPTERNAME" VARCHAR2(400 BYTE), 
	"PARAMS" VARCHAR2(2000 BYTE), 
	"UNIQUE_LEVEL" NUMBER(5,0), 
	"SHOW_ORDER" NUMBER(10,0), 
	"SHOW_HISTORY" NUMBER(5,0), 
	"ISSEARCHABLE" NUMBER(1,0), 
	"MASK" VARCHAR2(2000 BYTE), 
	"DEF_VALUE" VARCHAR2(255 BYTE), 
	"FLAGS" NUMBER(10,0) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PROPERTIES" VARCHAR2(4000 BYTE), 
	"RULES" NUMBER(10,0), 
	"TOOLTIP" VARCHAR2(1000 BYTE), 
	"AV_ADAPTER_NAME" VARCHAR2(400 BYTE), 
	"AV_ADAPTER_PROPERTIES" VARCHAR2(4000 BYTE), 
	"INTERNAL_NAME" VARCHAR2(200 BYTE), 
	 CONSTRAINT "XPKTT_ATTRIBUTES" PRIMARY KEY ("ATTR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  CREATE TABLE "TT_ATTR_OBJECT_TYPES" 
   (	"ATTR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"OBJECT_TYPE_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ISDISPLAYED" NUMBER(1,0) DEFAULT 0, 
	"REQUIRED" NUMBER(1,0) DEFAULT 0, 
	"OPTIONS" NUMBER DEFAULT 0, 
	"DEFAULT_VALUE" VARCHAR2(255 BYTE), 
	"FLAGS" NUMBER(10,0), 
	 CONSTRAINT "UNIQUE_ATTR_OBJECT_TYPES" UNIQUE ("ATTR_ID", "OBJECT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT), 
	 CONSTRAINT "R_43" FOREIGN KEY ("OBJECT_TYPE_ID")
	  REFERENCES "TT_OBJECT_TYPES" ("OBJECT_TYPE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "R_44" FOREIGN KEY ("ATTR_ID")
	  REFERENCES "TT_ATTRIBUTES" ("ATTR_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  CREATE TABLE "TT_REFERENCES" 
   (	"ATTR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"REFERENCE" NUMBER(20,0) NOT NULL ENABLE, 
	"OBJECT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"SHOW_ORDER" NUMBER(10,0), 
	"PRIORITY" NUMBER(10,0) DEFAULT NULL, 
	"ATTR_ACCESS_TYPE" NUMBER(10,0), 
	 CONSTRAINT "R_66" FOREIGN KEY ("REFERENCE")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "R_67" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "R_68" FOREIGN KEY ("ATTR_ID")
	  REFERENCES "TT_ATTRIBUTES" ("ATTR_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
  
  CREATE TABLE "TT_PARAMS" 
   (	"ATTR_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"OBJECT_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ATTR_ACCESS_TYPE" NUMBER(10,0) DEFAULT 0, 
	"VALUE" VARCHAR2(4000 BYTE), 
	"DATA" CLOB, 
	"SHOW_ORDER" NUMBER(10,0), 
	"DATE_VALUE" DATE, 
	"PRIORITY" NUMBER(10,0) DEFAULT 0,
	 CONSTRAINT "R_11" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "TT_OBJECTS" ("OBJECT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "R_6" FOREIGN KEY ("ATTR_ID")
	  REFERENCES "TT_ATTRIBUTES" ("ATTR_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 LOB ("DATA") STORE AS BASICFILE (
  CACHE 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;